### PR TITLE
Mock out empty virtualization mash

### PR DESCRIPTION
**Pull request by tas50**
This resolves spec failures on cookbooks that include build-essential as it's checking the virtualization values now

### CODE REVIEW

**Comment by sethvargo** [comment]
Similar to my other comment, I want to make sure we put this into the existing definitions before we start allowing new ones to have it

**Comment by tas50** [comment]
Let me add the backfill part.  That needs to go out as well.  I'd like to get a new gem cut and get it in ChefDK so I can resolve this build-essential chefspec mess I created on accident.

**Comment by sethvargo** [comment]
Yea, I'd like to get this + the omnibus locations all released as a new gem asap

**Comment by mfischer-zd** [comment]
:+1:

**Comment by sethvargo** [comment]
@tas50 @-me when you want another review on the backfill

**Comment by tas50** [comment]
@sethvargo Should be good now

**Pull request merged**
